### ISSUE TITLE
Butterfly's not lining up

### ISSUE THREAD

**Issue by drew0036** [drew0036/fancy-hover-boxes#1]
Hey @hellachella,

My butterflies boxes do not want to shrink so some reason. Any advice?

![Screen Shot 2020-11-18 at 10 12 22 AM](https://user-images.githubusercontent.com/55107709/99549221-69f63900-2987-11eb-8bf0-3bc74603ce4a.png)
![Screen Shot 2020-11-18 at 10 12 44 AM](https://user-images.githubusercontent.com/55107709/99549238-6d89c000-2987-11eb-9bc7-50ddbf989a60.png)
![Screen Shot 2020-11-18 at 10 12 55 AM](https://user-images.githubusercontent.com/55107709/99549239-6d89c000-2987-11eb-902b-fd53b740de99.png)

Thank you!

**Comment by drew0036** [comment]
@mackenzierose, can you take a look, please?

**Comment by drew0036** [comment]
Nevermind, got it! I was just missing the basic:

img {
display: flex;
width: 100%;
)

**Comment by MacKenzieRose** [comment]
Sorry for missing this! Glad you got it :)
